[package]
name = "habitat_butterfly"
version = "0.1.0"
authors = ["Adam Jacob <adam@chef.io>"]
build = "build.rs"
workspace = "../../"

[[bin]]
name = "butterfly"
doc = false

[build-dependencies]
pkg-config = "0.3"

[dependencies]
protobuf = "*"
rustc-serialize = "*"
rand = "*"
log = "*"
env_logger = "*"
time = "*"
threadpool = "*"

[dependencies.uuid]
version = "*"
features = ["rustc-serialize", "v4"]

[dependencies.habitat_net]
path = "../net"

[dependencies.habitat_core]
path = "../core"

[dependencies.zmq]
git = "https://github.com/erickt/rust-zmq.git"

[features]
functional = []
protocols = []

